# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require(File.join(File.dirname(__FILE__), 'config', 'boot'))

require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'

require 'tasks/rails'

desc 'Deploy to production server'
task :deploy do
  cd '..' do | dir|
    sh %{ rsync -avz -e ssh website-support thepfeil@thepfeils.com:/home/thepfeil/rails-apps }
  end
end
