<html>
<body>
<pre>
<h1>Build Log</h1>
<h3>
--------------------Configuration: EDITOR - Win32 (WCE x86em) Debug--------------------
</h3>
<h3>Command Lines</h3>
Creating command line "rc.exe /l 0x409 /fo"X86EMDbg/EDITOR.res" /d UNDER_CE=211 /d _WIN32_WCE=211 /d "UNICODE" /d "_UNICODE" /d "DEBUG" /d "WIN32_PLATFORM_HPCPRO" /d "_X86_" /d "x86" /d "i486" /r "C:\GOLD\LABS.HPC\Lab13b\EDITOR.rc"" 
Creating temporary file "C:\DOCUME~1\RENTAL~1\LOCALS~1\Temp\RSP4E7.tmp" with contents
[
commctrl.lib coredll.lib corelibc.lib /nologo /stack:0x10000,0x1000 /subsystem:windows /incremental:yes /pdb:"X86EMDbg/EDITOR.pdb" /debug /nodefaultlib:"OLDNAMES.lib" /nodefaultlib:libc.lib /nodefaultlib:libcd.lib /nodefaultlib:libcmt.lib /nodefaultlib:libcmtd.lib /nodefaultlib:msvcrt.lib /nodefaultlib:msvcrtd.lib /nodefaultlib:oldnames.lib /out:"X86EMDbg/EDITOR.exe" /windowsce:emulation /MACHINE:IX86 
.\X86EMDbg\EDITOR.obj
.\X86EMDbg\StdAfx.obj
.\X86EMDbg\EDITOR.res
]
Creating command line "link.exe @C:\DOCUME~1\RENTAL~1\LOCALS~1\Temp\RSP4E7.tmp"
<h3>Output Window</h3>
Compiling resources...
Linking...



<h3>Results</h3>
EDITOR.exe - 0 error(s), 0 warning(s)
</pre>
</body>
</html>
