//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Contacts.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_CONTACTS_FORM               101
#define IDC_SIGNATURE                   101
#define IDS_EDIT                        102
#define IDC_BROWSER                     102
#define IDS_TOOL                        103
#define IDM_MENU                        104
#define IDR_MAIN_EDIT                   105
#define IDR_MAIN_TOOL                   106
#define IDR_MAINFRAME                   128
#define IDD_SIGNATURE                   130
#define IDD_CALL                        133
#define IDB_FORM                        134
#define IDB_SIGNATURE                   135
#define IDB_VIOXX2                      138
#define IDB_VIOXX                       139
#define IDD_CUSTOMER                    139
#define IDB_VIOXX1                      140
#define IDD_CALL_DETAILS                140
#define IDD_CALL_NOTES                  141
#define IDD_CALL_SAMPLES                142
#define IDB_ADD_SAMPLE                  143
#define IDD_CALL_TOPICS                 144
#define IDD_ADD_SAMPLE                  146
#define IDB_DELETE_SAMPLE               147
#define IDD_CALL_PIN                    148
#define IDD_CALL_SAMPLE_SIGNATURE       149
#define IDD_TODAY_VIEW                  150
#define IDB_LEGAL                       151
#define IDB_CLEAR                       153
#define IDB_DONE                        154
#define IDB_CHECKS                      155
#define IDB_INSIGHT                     156
#define IDD_CONTACTS                    157
#define IDD_PROFILE                     158
#define IDD_ADD_CUSTOMER                159
#define IDR_POPUP                       160
#define IDB_TAPE                        161
#define IDD_CALL_TIME                   162
#define IDC_CUST_LIST                   1000
#define IDC_FILTER                      1001
#define IDC_IJK                         1003
#define IDC_AB                          1004
#define IDC_UVW                         1005
#define IDC_COMBO1                      1006
#define IDC_RST                         1007
#define IDC_OPQ                         1008
#define IDC_SAMPLES                     1008
#define IDC_LMN                         1009
#define IDC_CLEAR                       1009
#define IDC_CDE                         1010
#define IDC_CALL_DATE                   1010
#define IDC_FGH                         1011
#define IDC_CALL_NAME                   1011
#define IDC_XYZ                         1012
#define IDC_REPRINTS_LABEL              1012
#define IDC_DONE                        1012
#define IDC_CALL_ADDRESS                1013
#define IDC_CALL_CSZ                    1014
#define IDC_CALL_LICENSE                1015
#define IDC_CALL_LICENSE_LABEL          1016
#define IDC_CALL_DETAILS_LABEL          1017
#define IDC_CALL_TOPICS_LABEL           1018
#define IDC_CALL_SAMPLES_LABEL          1019
#define IDC_CALL_PIR_LABEL              1020
#define IDC_CALL_NOTES                  1021
#define IDC_CALL_DETAILS                1022
#define IDC_CALL_TOPICS                 1023
#define IDC_CALL_SAMPLES                1024
#define IDC_CALL_PIR                    1025
#define IDC_CALL_REPRINT                1026
#define IDC_CALL_FORM                   1027
#define IDC_CALL_SIGNATURE              1028
#define IDC_DETAILS_VIOXX               1030
#define IDC_DETAILS_ZOCOR               1031
#define IDC_DETAILS_MAXALT              1032
#define IDC_CALL_SAMPLE_LIST            1032
#define IDC_CALL_REPORT                 1032
#define IDC_ADD_SAMPLE                  1033
#define IDC_SAMPLE_LIST                 1034
#define IDC_DELETE_SAMPLE               1034
#define IDC_SAMPLE_QTY                  1035
#define IDC_SAMPLE_LOT                  1036
#define IDC_CALL_PIN                    1037
#define IDC_SIGNATURE_BITMAP            1038
#define IDC_PIN_1                       1040
#define IDC_PIN_2                       1041
#define IDC_PIN_3                       1042
#define IDC_PIN_4                       1043
#define IDC_PIN_5                       1044
#define IDC_PIN_6                       1045
#define IDC_PIN_7                       1046
#define IDC_VOICE                       1046
#define IDC_PIN_8                       1047
#define IDC_PIN_9                       1048
#define IDC_PIN_0                       1049
#define IDC_CALL_TIME                   1049
#define IDC_CALL_DURATION               1050
#define IDC_TODAY_CALL_DATE             1075
#define IDC_CALL_CUSTOMER               1091
#define IDR_MAIN_NEW                    32772
#define IDS_CAP_NEW                     32774
#define ID_NEW_CUSTOMER                 32775
#define ID_NEW_CALL                     32776
#define IDS_CAP_MENUITEM32778           32779
#define IDS_VIEW                        32781
#define IDR_MAIN_VIEW                   32782
#define ID_VIEW_PROFILE                 32783
#define ID_VIEW_CUSTOMER                32785
#define IDS_NEW                         65000
#define IDS_FILE                        65001
#define IDS_MHELP                       65002
#define IDS_SAVE                        65003
#define IDS_CUT                         65004
#define IDS_COPY                        65005
#define IDS_PASTE                       65006
#define IDS_ABOUT                       65007

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        163
#define _APS_NEXT_COMMAND_VALUE         32786
#define _APS_NEXT_CONTROL_VALUE         1050
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
