# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require(File.join(File.dirname(__FILE__), 'config', 'boot'))

require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'

require 'tasks/rails'

namespace 'deploy' do

  desc 'Deploy to thepfeils.com server'
  task :thepfeils do
    cd '..' do | dir|
      sh %{ rsync -avz -e ssh iSFA thepfeil@thepfeils.com:/home/thepfeil/rails-apps }
    end
  end

  desc 'Deploy to iapps server'
  task :iapps do
    cd '..' do |dir|
      sh %{ rsync -avz -e ssh iSFA notroot@iapps:/var/rails-apps }
    end
  end

end
