# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require(File.join(File.dirname(__FILE__), 'config', 'boot'))

require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'

require 'tasks/rails'

namespace 'deploy' do
  APP_NAME = 'jruby_on_rails_app'
  WEBAPPS_DIR = '/Developer/apache-tomcat/Versions/apache-tomcat-5.5.26/webapps'
  
  desc 'deploy to local tomcat instance'
  task :local do
    `jruby -S rake war:clean`
    `jruby -S rake war`
    `tomcat_ctl stop`
    rm_f "#{WEBAPPS_DIR}/#{APP_NAME}.war"
    rm_rf "#{WEBAPPS_DIR}/#{APP_NAME}"
    cp "#{APP_NAME}.war", WEBAPPS_DIR
    `tomcat_ctl start` 
  end
  
end