# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require(File.join(File.dirname(__FILE__), 'config', 'boot'))

require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'

require 'tasks/rails'

desc "deletes all people from database and reloads them from LDAP"
task :reload_people do
  system %q{ ruby script\runner 'PersonServices.reload_people' -e development }
end