# the following is system depedent
GNUSTEP_MAKEFILES=/usr/share/GNUstep/Makefiles

include $(GNUSTEP_MAKEFILES)/common.make

APP_NAME = HelloWorld
HelloWorld_HEADERS = 
HelloWorld_OBJC_FILES = HelloWorld.m
HelloWorld_RESOURCE_FILES = 

include $(GNUSTEP_MAKEFILES)/application.make
