# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 5) do

  create_table "categories", :force => true do |t|
    t.column "name", :string
  end

  create_table "priorities", :force => true do |t|
    t.column "name",     :string
    t.column "priority", :integer
  end

  create_table "tasks", :force => true do |t|
    t.column "user_id",     :integer,                                     :null => false
    t.column "category_id", :integer,                                     :null => false
    t.column "priority_id", :integer,                                     :null => false
    t.column "title",       :string
    t.column "notes",       :text
    t.column "due",         :date
    t.column "created",     :datetime
    t.column "updated",     :datetime, :default => '2007-12-02 19:54:14'
    t.column "completed",   :datetime
  end

  create_table "users", :force => true do |t|
    t.column "username", :string
    t.column "password", :string
  end

end
