<html>
<body>
<pre>
<h1>Build Log</h1>
<h3>
--------------------Configuration: STARTAPP - Win32 (WCE MIPS) Debug--------------------
</h3>
<h3>Command Lines</h3>
Creating command line "rc.exe /l 0x409 /fo"MIPSDbg/STARTAPP.res" /d UNDER_CE=300 /d _WIN32_WCE=300 /d "UNICODE" /d "_UNICODE" /d "DEBUG" /d "WIN32_PLATFORM_PSPC" /d "MIPS" /d "_MIPS_" /r "C:\WINCE\LABS.PPC\lab11c\STARTAPP.rc"" 
Creating temporary file "C:\WINNT\Profiles\Paul\LOCALS~1\Temp\RSP2AF.tmp" with contents
[
commctrl.lib coredll.lib  aygshell.lib /nologo /base:"0x00010000" /stack:0x10000,0x1000 /entry:"WinMainCRTStartup" /incremental:yes /pdb:"MIPSDbg/STARTAPP.pdb" /debug /nodefaultlib:"libc.lib /nodefaultlib:libcd.lib /nodefaultlib:libcmt.lib /nodefaultlib:libcmtd.lib /nodefaultlib:msvcrt.lib /nodefaultlib:msvcrtd.lib /nodefaultlib:oldnames.lib" /out:"MIPSDbg/STARTAPP.exe" /subsystem:windowsce,3.00 /MACHINE:MIPS  
.\MIPSDbg\StdAfx.obj
.\MIPSDbg\STARTAPP.res
.\MIPSDbg\STARTAPP.obj
]
Creating command line "link.exe @C:\WINNT\Profiles\Paul\LOCALS~1\Temp\RSP2AF.tmp"
<h3>Output Window</h3>
Compiling resources...
Linking...



<h3>Results</h3>
STARTAPP.exe - 0 error(s), 0 warning(s)
</pre>
</body>
</html>
