class CreatePeople < ActiveRecord::Migration
  def self.up
    create_table :people do |t|
      t.string :assignmentcontact
      t.string :assignmentcontactcn
      t.string :businessdivision
      t.string :businessdivisioncode
      t.string :cn
      t.string :co
      t.string :contractagency
      t.string :contractagencycode
      t.string :countrycode
      t.string :departmentNumber
      t.string :departmentname
      t.string :description
      t.string :dn
      t.string :dnum
      t.string :employeeNumber
      t.string :empnonempind
      t.string :facsimileTelephoneNumber
      t.string :formalmiddlename
      t.string :formalnamesuffix
      t.string :formalsalutation
      t.string :givenName
      t.string :hrinfosourcecode
      t.string :inetemailflag
      t.string :l
      t.string :lablocation
      t.string :mail
      t.string :manager
      t.string :managercn
      t.string :mobile
      t.string :mrkBusinessUnitDesc
      t.string :mrkBusinessUnitID
      t.string :mrkBusinessUnitName
      t.string :mrkBusinessUnitSetID
      t.string :mrkCWDesc
      t.string :mrkCWType
      t.string :mrkCompanyDesc
      t.string :mrkCompanyID
      t.string :mrkCompanyName
      t.string :mrkDivisionDesc
      t.string :mrkDivisionID
      t.string :mrkDivisionName
      t.string :mrkFSRBG
      t.string :mrkFSTerritoryAssignmentEffectiveDate
      t.string :mrkJobCodeSetID
      t.string :mrkOrgDesc
      t.string :mrkOrgID
      t.string :mrkOrgName
      t.string :mrkPKISubscriberAgreementFlag
      t.string :mrkPKIa1
      t.string :mrkPKIa2
      t.string :mrkPositionSetID
      t.string :mrkRevoked
      t.string :mrkRevokedEffective
      t.string :mrkRevokedLastModified
      t.string :mrkRole
      t.string :mrkSrchFirstName
      t.string :mrkSrchLastName
      t.string :mrkSubDivisionDesc
      t.string :mrkSubDivisionID
      t.string :mrkSubDivisionName
      t.string :mrkSuperDivisionDesc
      t.string :mrkSuperDivisionID
      t.string :mrkSuperDivisionName
      t.string :mrkSuperOrgDesc
      t.string :mrkSuperOrgID
      t.string :mrkSuperOrgName
      t.string :mrkVisible
      t.string :mrkdisplayname1
      t.string :mrkdisplayname2
      t.string :mrkmsxmail
      t.string :mrkselfservefirstvisited
      t.string :mrkselfservelastconfirmed
      t.string :mrkselfservelastedited
      t.string :mrkselfservelastvisited
      t.string :mrksubdivision
      t.string :mrksubdivisioncode
      t.string :mvxnumber
      t.string :nickname
      t.string :nicknameuseind
      t.string :ntUserDomainId
      t.string :ntdomain
      t.string :pager
      t.string :physicalDeliveryOfficeName
      t.string :positiontitlenumber
      t.string :preferredfirstname
      t.string :preferredlastname
      t.string :preferredmiddlename
      t.string :preferrednamequalifier
      t.string :preferrednamesuffix
      t.string :preferredsalutation
      t.string :roomNumber
      t.string :secretary
      t.string :secretarycn
      t.string :securidexpdate
      t.string :securidserialnum
      t.string :sitecode
      t.string :sn
      t.string :telephoneNumber2
      t.string :telephoneNumber
      t.string :title
      t.string :uid
      t.integer :version

      t.timestamps
    end
  end

  def self.down
    drop_table :people
  end
end
