<html>
<body>
<pre>
<h1>Build Log</h1>
<h3>
--------------------Configuration: PAGEALLOC - Win32 (WCE x86em) Debug--------------------
</h3>
<h3>Command Lines</h3>
Creating command line "rc.exe /l 0x409 /fo"X86EMDbg/OPEN.res" /d UNDER_CE=300 /d _WIN32_WCE=300 /d "UNICODE" /d "_UNICODE" /d "DEBUG" /d "WIN32_PLATFORM_PSPC" /d "_X86_" /d "x86" /d "i486" /r "c:\gold\labs.ppc\Lab17c\OPEN.RC"" 
Creating temporary file "C:\DOCUME~1\RENTAL~1\LOCALS~1\Temp\RSP21A.tmp" with contents
[
corelibc.lib commctrl.lib coredll.lib aygshell.lib commdlg.lib /nologo /stack:0x10000,0x1000 /subsystem:windows /incremental:yes /pdb:"X86EMDbg/PAGEALLOC.pdb" /debug /nodefaultlib:"OLDNAMES.lib" /nodefaultlib:libc.lib /nodefaultlib:libcd.lib /nodefaultlib:libcmt.lib /nodefaultlib:libcmtd.lib /nodefaultlib:msvcrt.lib /nodefaultlib:msvcrtd.lib /nodefaultlib:oldnames.lib /out:"X86EMDbg/PAGEALLOC.exe" /windowsce:emulation /MACHINE:IX86 
.\X86EMDbg\OPEN.OBJ
.\X86EMDbg\STDAFX.OBJ
.\X86EMDbg\OPEN.res
]
Creating command line "link.exe @C:\DOCUME~1\RENTAL~1\LOCALS~1\Temp\RSP21A.tmp"
<h3>Output Window</h3>
Compiling resources...
Linking...



<h3>Results</h3>
PAGEALLOC.exe - 0 error(s), 0 warning(s)
</pre>
</body>
</html>
