package HelloApp;


/**
* HelloApp/HelloOperations.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from Hello.idl
* Friday, April 5, 2002 12:05:01 PM EST
*/

public interface HelloOperations 
{
  String sayHello ();
} // interface HelloOperations
