//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by TIMELOG.rc
//
#define IDS_APP_TITLE                   1
#define IDS_HELLO                       2
#define IDC_TIMELOG                     3
#define IDI_TIMELOG                     101
#define IDM_MENU                        102
#define IDD_ABOUTBOX                    103
#define IDD_TALL                        103
#define IDD_WIDE                        104
#define IDC_GO                          1001
#define IDC_STOP                        1002
#define IDC_GO_FIRST                    1003
#define IDC_GO_PREV                     1004
#define IDC_GO_NEXT                     1005
#define IDC_GO_LAST                     1006
#define IDC_PROJECT                     1007
#define IDC_TASK                        1009
#define IDC_NOTE                        1010
#define IDC_DATE                        1011
#define IDC_START_TIME                  1012
#define IDC_WORK_TIME                   1013
#define IDC_ELAPSED_TIME                1014
#define IDC_CURRENT_NO                  1015
#define IDC_TOTAL_COUNT                 1016
#define IDC_STOP_TIME                   1017
#define IDC_START                       1018
#define IDC_DELETE                      1019
#define IDC_RECORD                      1020
#define IDC_CLEAR                       1021
#define IDM_FILE_EXIT                   40002
#define IDM_HELP_ABOUT                  40003

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        104
#define _APS_NEXT_COMMAND_VALUE         40004
#define _APS_NEXT_CONTROL_VALUE         1023
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
