//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by IComp.rc
//
#define IDD_ABOUTBOX                    100
#define IDC_HTMLWND                     101
#define IDB_GRID                        104
#define IDR_MAINFRAME                   128
#define IDR_X                           129
#define IDB_VIEWS                       130
#define IDB_DUMMY                       131
#define IDD_CUSTOMER_VIEW               132
#define IDB_VIOXX_FLIP                  132
#define IDR_MAINFRAME2                  133
#define IDB_FLIP                        133
#define IDB_FLIP_FLIP                   134
#define IDD_CALL_DIALOG                 136
#define IDD_SIGNATURE_DIALOG            137
#define IDB_VIOXX                       139
#define IDB_SIGNATURE                   140
#define IDD_FORM_NUMBER_DLG             141
#define IDD_TODAY_VIEW                  142
#define IDB_IDS                         143
#define IDC_TABS                        1000
#define IDC_123                         1001
#define IDC_ABC                         1002
#define IDC_DEF                         1003
#define IDC_GHI                         1004
#define IDC_JKL                         1005
#define IDC_MNO                         1006
#define IDC_PQRS                        1007
#define IDC_TUV                         1008
#define IDC_WXYZ                        1009
#define IDC_CUST_LIST                   1010
#define IDC_CALL                        1011
#define IDC_AVAILABLE_SAMPLES           1014
#define IDC_SAMPLED_PRODUCTS            1015
#define IDC_SAMPLE_ADD                  1016
#define IDC_SAMPLE_REMOVE               1017
#define IDC_SAMPLE_REMOVE_ALL           1018
#define IDC_SAMPLE_SIGNATURE            1019
#define IDC_SAMPLE_FORM_NUMBER          1020
#define IDC_PAPER_RECEIPT_REQUESTED     1021
#define IDC_ERECEIPT_REQUESTED          1022
#define IDC_AVAILABLE_SAMPLES_LABEL     1023
#define IDC_SAMPLED_PRODUCTS_LABEL      1024
#define IDC_AVAILABLE_DETAILS_LABEL     1025
#define IDC_LOCATION                    1026
#define IDC_AVAILABLE_DETAILS           1026
#define IDC_SAMPLES                     1027
#define IDC_DETAIL_ADD                  1027
#define IDC_RECEIPT_REQUESTED           1028
#define IDC_DETAIL_REMOVE               1028
#define IDC_SIGNATURE_CLEAR             1029
#define IDC_DETAIL_REMOVE_ALL           1029
#define IDC_SIGNATURE                   1030
#define IDC_LOGO                        1030
#define IDC_DETAILED_PRODUCTS_LABEL     1030
#define IDC_LICENSE                     1031
#define IDC_DETAILED_PRODUCTS           1031
#define IDC_BUTTON1                     1032
#define IDC_ID_NEW                      1032
#define IDC_SIGNATURE_FLIP              1032
#define IDC_ADD_CALL_TOPIC              1032
#define IDC_CALL_REPORT                 1032
#define IDC_CALL_DATE                   1033
#define IDC_ID_DELETE                   1033
#define IDC_DETAIL_REQUESTED            1033
#define IDC_FORM_NUMBER                 1034
#define IDC_ID_EDIT                     1034
#define IDC_REMOVE_CALL_TOPIC           1034
#define IDC_CONFIRM_FORM_NUMBER         1035
#define IDC_ADD_ALL_CALL_TOPIC          1035
#define IDC_FLAG_NEW                    1036
#define IDC_REMOVE_ALL_CALL_TOPIC       1036
#define IDC_FIRST_NAME                  1037
#define IDC_FIRST_NAME_LABEL            1038
#define IDC_MID_INITAL_LABEL            1039
#define IDC_FLAG_DELETE                 1039
#define IDC_LAST_NAME_LABEL             1041
#define IDC_LAST_NAME                   1042
#define IDC_ORG_NAME_LABEL              1043
#define IDC_ORG_NAME                    1044
#define IDC_GEN_INFO                    1045
#define IDC_IDS                         1046
#define IDC_FLAGS                       1047
#define IDC_FLAG_TYPE                   1048
#define IDC_FLAG_TYPE_LABEL             1049
#define IDC_NOTES                       1050
#define IDC_LOCATION_PHONE              1051
#define IDC_LOCATION_LINE2              1052
#define IDC_LOCATION_CITY               1053
#define IDC_LOCATION_STATE              1054
#define IDC_LOCATION_ZIP                1055
#define IDC_LOCATION_PHONE_LABEL        1057
#define IDC_LOCATION_LINE1              1058
#define IDC_LOCATION_FAX                1061
#define IDC_LOCATION_FAX_LABEL          1062
#define IDC_BUTTON2                     1063
#define IDC_PROFILE_LIST                1064
#define IDC_SAMPLE_INSTRUCTIONS         1065
#define IDC_TAB1                        1066
#define IDC_CALL_NOTE_TAB               1066
#define IDC_CALL_STRATEGY               1067
#define IDC_NEXT_CALL_STRATEGY          1068
#define IDC_CALL_ACCOMPLISHMENTS        1069
#define IDC_CALL_HISTORICAL_NOTES       1070
#define IDC_CALL_PERSONAL_NOTES         1071
#define IDC_BUTTON3                     1072
#define IDC_CALL_DATE_LABEL             1073
#define IDC_CALL_DATE1                  1074
#define IDC_TODAY_CALL_DATE             1075
#define IDC_CALL_LOCATION_LABEL         1076
#define IDC_CALL_LOCATION               1077
#define IDC_CALL_START_TIME_LABEL       1078
#define IDC_CALL_START_TIME             1079
#define IDC_CALL_END_TIME_LABEL         1080
#define IDC_CALL_END_TIME               1081
#define IDC_CALL_CONTACT_LABEL          1082
#define IDC_CALL_CONTACT                1083
#define IDC_CALL_DEPT_LABEL             1084
#define IDC_CALL_DEPT                   1085
#define IDC_CALL_COUNT_LABEL            1086
#define IDC_CALL_COUNT_SPIN             1087
#define IDC_CALL_COUNT                  1088
#define IDC_SELECTED_CALL_TOPICS        1089
#define IDC_AVAILABLE_CALL_TOPICS_LABEL 1090
#define IDC_AVAILABLE_CALL_TOPICS2      1091
#define IDC_CALL_CUSTOMER               1091
#define IDC_SELECTED_CALL_TOPICS_LABEL  1092
#define ID_PREVIOUS                     32772
#define ID_NEXT                         32773
#define ID_CUSTOMER                     32774
#define ID_CALL                         32775
#define ID_GO_BACK                      32776
#define ID_GO_FORWARD                   32777
#define ID_GO_CALENDAR                  32779
#define ID_GO_CUSTOMERS                 32780
#define ID_VIEW_GRID                    32783

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        144
#define _APS_NEXT_COMMAND_VALUE         32784
#define _APS_NEXT_CONTROL_VALUE         1092
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
