// ------------------------------------------------------------------------------
//<autogenerated>
//        This code was generated by Microsoft Visual Studio Team System 2005.
//
//        Changes to this file may cause incorrect behavior and will be lost if
//        the code is regenerated.
//</autogenerated>
//------------------------------------------------------------------------------
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace TestProject1
{
[System.Diagnostics.DebuggerStepThrough()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TestTools.UnitTestGeneration", "1.0.0.0")]
internal class BaseAccessor {
    
    protected Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject m_privateObject;
    
    protected BaseAccessor(object target, Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType type) {
        m_privateObject = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject(target, type);
    }
    
    protected BaseAccessor(Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType type) : 
            this(null, type) {
    }
    
    internal virtual object Target {
        get {
            return m_privateObject.Target;
        }
    }
    
    public override string ToString() {
        return this.Target.ToString();
    }
    
    public override bool Equals(object obj) {
        if (typeof(BaseAccessor).IsInstanceOfType(obj)) {
            obj = ((BaseAccessor)(obj)).Target;
        }
        return this.Target.Equals(obj);
    }
    
    public override int GetHashCode() {
        return this.Target.GetHashCode();
    }
}


[System.Diagnostics.DebuggerStepThrough()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TestTools.UnitTestGeneration", "1.0.0.0")]
internal class Visual_Studio_2005_Unit_Testing_Examples_PersonAccessor : BaseAccessor {
    
    protected static Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType m_privateType = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType(typeof(global::Visual_Studio_2005_Unit_Testing_Examples.Person));
    
    internal Visual_Studio_2005_Unit_Testing_Examples_PersonAccessor(global::Visual_Studio_2005_Unit_Testing_Examples.Person target) : 
            base(target, m_privateType) {
    }
    
    internal string _fullName {
        get {
            string ret = ((string)(m_privateObject.GetField("_fullName")));
            return ret;
        }
        set {
            m_privateObject.SetField("_fullName", value);
        }
    }
    
    internal global::System.DateTime _dateOfBirth {
        get {
            global::System.DateTime ret = ((global::System.DateTime)(m_privateObject.GetField("_dateOfBirth")));
            return ret;
        }
        set {
            m_privateObject.SetField("_dateOfBirth", value);
        }
    }
    
    internal static int MaxAge {
        get {
            int ret = ((int)(m_privateType.GetStaticField("MaxAge")));
            return ret;
        }
        set {
            m_privateType.SetStaticField("MaxAge", value);
        }
    }
}
}
