//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by command.rc
//
#define IDS_APP_TITLE                   1
#define IDS_HELLO                       2
#define IDC_COMMAND                     3
#define IDI_COMMAND                     101
#define IDM_MENU                        102
#define IDD_ABOUTBOX                    103
#define IDS_HELP                        104
#define IDS_COMMAND1                    301
#define IDM_MAIN_COMMAND1               40001
#define IDM_HELP_ABOUT                  40003
#define IDM_NEW                         40004
#define View                            40005
#define IDS_CAP_VIEW                    40007
#define IDM_VIEW_AGENDA                 40008
#define IDM_VIEW_DAY                    40009
#define IDM_VIEW_WEEK                   40010
#define IDM_VIEW_MONTH                  40011
#define IDM_VIEW_YEAR                   40012
#define ID_TOOLS                        40013
#define IDS_CAP_TOOLS                   40015
#define IDM_TOOLS_RECEIVE               40016
#define IDM_TOOLS_OPTIONS               40017
#define IDM_POPUP_VIEW                  40018
#define IDM_POPUP_TOOLS                 40019

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        104
#define _APS_NEXT_COMMAND_VALUE         40020
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
