GNUSTEP_MAKEFILES=/usr/share/GNUstep/Makefiles

include $(GNUSTEP_MAKEFILES)/common.make

APP_NAME = FoundationLibraryExploring
$(APP_NAME)_HEADERS = 
$(APP_NAME)_OBJC_FILES = main.m
$(APP_NAME)_RESOURCE_FILES = 

include $(GNUSTEP_MAKEFILES)/application.make

include ../common.make

