<html>
<body>
<pre>
<h1>Build Log</h1>
<h3>
--------------------Configuration: PRINT - Win32 (WCE ARM) Debug--------------------
</h3>
<h3>Command Lines</h3>
Creating temporary file "C:\DOCUME~1\RENTAL~1\LOCALS~1\Temp\RSP5A0.tmp" with contents
[
/nologo /W3 /Zi /Od /D "DEBUG" /D "ARM" /D "_ARM_" /D UNDER_CE=211 /D _WIN32_WCE=211 /D "WIN32_PLATFORM_HPCPRO" /D "UNICODE" /D "_UNICODE" /Fp"ARMDbg/PRINT.pch" /Yu"stdafx.h" /Fo"ARMDbg/" /Fd"ARMDbg/" /MC /c 
"C:\WINCE\LABS.HPC\Lab15c\PRINT.cpp"
]
Creating command line "clarm.exe @C:\DOCUME~1\RENTAL~1\LOCALS~1\Temp\RSP5A0.tmp" 
Creating temporary file "C:\DOCUME~1\RENTAL~1\LOCALS~1\Temp\RSP5A1.tmp" with contents
[
commctrl.lib coredll.lib commdlg.lib /nologo /base:"0x00010000" /stack:0x10000,0x1000 /entry:"WinMainCRTStartup" /incremental:yes /pdb:"ARMDbg/PRINT.pdb" /debug /nodefaultlib:"libc.lib /nodefaultlib:libcd.lib /nodefaultlib:libcmt.lib /nodefaultlib:libcmtd.lib /nodefaultlib:msvcrt.lib /nodefaultlib:msvcrtd.lib /nodefaultlib:oldnames.lib" /out:"ARMDbg/PRINT.exe" /subsystem:windowsce,2.11 /align:"4096" /MACHINE:ARM 
.\ARMDbg\PRINT.obj
.\ARMDbg\StdAfx.obj
.\ARMDbg\PRINT.res
]
Creating command line "link.exe @C:\DOCUME~1\RENTAL~1\LOCALS~1\Temp\RSP5A1.tmp"
<h3>Output Window</h3>
Compiling...
PRINT.cpp
Linking...



<h3>Results</h3>
PRINT.exe - 0 error(s), 0 warning(s)
</pre>
</body>
</html>
