<html>
<body>
<pre>
<h1>Build Log</h1>
<h3>
--------------------Configuration: READFILE - Win32 (WCE x86em) Debug--------------------
</h3>
<h3>Command Lines</h3>
Creating temporary file "C:\DOCUME~1\RENTAL~1\LOCALS~1\Temp\RSP312.tmp" with contents
[
/nologo /W3 /GX- /Zi /Od /D "DEBUG" /D "i486" /D UNDER_CE=211 /D _WIN32_WCE=211 /D "WIN32" /D "STRICT" /D "_WIN32_WCE_EMULATION" /D "INTERNATIONAL" /D "USA" /D "INTLMSG_CODEPAGE" /D "WIN32_PLATFORM_HPCPRO" /D "UNICODE" /D "_UNICODE" /D "_X86_" /D "x86" /Fp"X86EMDbg/READFILE.pch" /Yu"stdafx.h" /Fo"X86EMDbg/" /Fd"X86EMDbg/" /Gz /c 
"C:\gold\LABS.HPC\LAB17A\OPEN.cpp"
]
Creating command line "cl.exe @C:\DOCUME~1\RENTAL~1\LOCALS~1\Temp\RSP312.tmp" 
Creating temporary file "C:\DOCUME~1\RENTAL~1\LOCALS~1\Temp\RSP313.tmp" with contents
[
corelibc.lib commctrl.lib coredll.lib commdlg.lib /nologo /stack:0x10000,0x1000 /subsystem:windows /incremental:yes /pdb:"X86EMDbg/READFILE.pdb" /debug /nodefaultlib:"OLDNAMES.lib" /nodefaultlib:libc.lib /nodefaultlib:libcd.lib /nodefaultlib:libcmt.lib /nodefaultlib:libcmtd.lib /nodefaultlib:msvcrt.lib /nodefaultlib:msvcrtd.lib /nodefaultlib:oldnames.lib /out:"X86EMDbg/READFILE.exe" /windowsce:emulation /MACHINE:IX86  
.\X86EMDbg\StdAfx.obj
.\X86EMDbg\OPEN.res
.\X86EMDbg\OPEN.obj
]
Creating command line "link.exe @C:\DOCUME~1\RENTAL~1\LOCALS~1\Temp\RSP313.tmp"
<h3>Output Window</h3>
Compiling...
OPEN.cpp
Linking...



<h3>Results</h3>
READFILE.exe - 0 error(s), 0 warning(s)
</pre>
</body>
</html>
