WM_LBUTTONDOWN
void
OnLButtonDown
(HWND hWnd, BOOL fDoubleClick, int x, int y, UINT keyFlags)
    if (fDoubleClick) // WM_LBUTTONDBLCLK
    {
    }
    else              // WM_LBUTTONDOWN
    {
    }
