//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MESSAGES.RC
//

#define IDCOPY                          1001
#define IDC_LIST1                       1002
#define IDABOUT                         1003
#define IDSETUP                         1004
#define IDC_EDIT                        1005
#define IDC_COMMENT                     1006

#define IDD_MESSAGES                    101
#define IDD_SETUP                       102

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1007
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
