//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by CRACKERS.RC
//
#define IDD_COMMENTBLOCK                102
#define IDD_EDITMSGLIST                 103
#define IDPROPERTY                      1007
#define IDC_ADD                         1008
#define IDC_REMOVE                      1009
#define IDC_CHANGE                      1010
#define IDC_RESET                       1011
#define IDC_MESSAGE                     1012
#define IDC_FNNAME                      1013
#define IDC_PARAMETERS                  1014
#define IDC_CODE                        1015
#define IDC_RETTYPE                     1016
#define IDC_CLEAR                       1018
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        104
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1018
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
