GNUSTEP_MAKEFILES=/usr/share/GNUstep/Makefiles

include $(GNUSTEP_MAKEFILES)/common.make

APP_NAME = Fraction
$(APP_NAME)_HEADERS = Fraction.h
$(APP_NAME)_OBJC_FILES = Fraction.m main.m
$(APP_NAME)_RESOURCE_FILES = 

include $(GNUSTEP_MAKEFILES)/application.make

include ../common.make

