<html>
<body>
<pre>
<h1>Build Log</h1>
<h3>
--------------------Configuration: HEAPALLOC - Win32 (WCE x86em) Debug--------------------
</h3>
<h3>Command Lines</h3>
Creating temporary file "C:\DOCUME~1\RENTAL~1\LOCALS~1\Temp\RSP343.tmp" with contents
[
corelibc.lib commctrl.lib coredll.lib commdlg.lib /nologo /stack:0x10000,0x1000 /subsystem:windows /incremental:yes /pdb:"X86EMDbg/HEAPALLOC.pdb" /debug /nodefaultlib:"OLDNAMES.lib" /nodefaultlib:libc.lib /nodefaultlib:libcd.lib /nodefaultlib:libcmt.lib /nodefaultlib:libcmtd.lib /nodefaultlib:msvcrt.lib /nodefaultlib:msvcrtd.lib /nodefaultlib:oldnames.lib /out:"X86EMDbg/HEAPALLOC.exe" /windowsce:emulation /MACHINE:IX86  
.\X86EMDbg\StdAfx.obj
.\X86EMDbg\OPEN.res
.\X86EMDbg\OPEN.obj
]
Creating command line "link.exe @C:\DOCUME~1\RENTAL~1\LOCALS~1\Temp\RSP343.tmp"
<h3>Output Window</h3>
Linking...



<h3>Results</h3>
HEAPALLOC.exe - 0 error(s), 0 warning(s)
</pre>
</body>
</html>
