//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by CEFUN.rc
//
#define IDS_APP_TITLE                   1
#define IDS_HELLO                       2
#define IDC_CEFUN                       3
#define IDI_CEFUN                       101
#define IDM_MENU                        102
#define IDD_ABOUTBOX                    103
#define IDD_TALL                        103
#define IDD_WIDE                        104
#define IDC_LIBRARIES                   1001
#define IDC_FUNCTIONS                   1002
#define IDC_ABOUT                       1004
#define IDC_SAVE                        1005
#define IDC_SHOW                        1011
#define IDM_FILE_EXIT                   40002
#define IDM_HELP_ABOUT                  40003

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        105
#define _APS_NEXT_COMMAND_VALUE         40004
#define _APS_NEXT_CONTROL_VALUE         1013
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
