//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Options.rc
//
#define IDS_APP_TITLE                   1
#define IDS_HELLO                       2
#define IDC_OPTIONS                     3
#define IDI_OPTIONS                     101
#define IDM_MENU                        102
#define IDD_ABOUTBOX                    103
#define IDS_HELP                        104
#define IDD_OPTIONS                     104
#define IDS_COMMAND1                    301
#define IDC_COMBO1                      1001
#define IDC_COMBODAY                    1001
#define IDC_COMBO2                      1002
#define IDC_COMBOWEEK                   1002
#define IDC_CHECK1                      1003
#define IDC_CHECK2                      1004
#define IDC_CHECK3                      1005
#define IDC_CHECK4                      1006
#define IDC_COMBOTIME                   1007
#define IDC_COMBO4                      1008
#define IDC_COMBOUNITS                  1008
#define IDC_COMBOREQUESTS               1011
#define IDC_COMBOSEND                   1011
#define IDM_MAIN_COMMAND1               40001
#define IDM_HELP_ABOUT                  40003
#define IDM_TOOLS_OPTIONS               40004

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        105
#define _APS_NEXT_COMMAND_VALUE         40005
#define _APS_NEXT_CONTROL_VALUE         1012
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
